---
- hosts: sunbird-db
  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/sagarpatke/sunbird-devops.git
        dest: ~/sunbird-devops
        version: provisioning-1.8.2
      ignore_errors: yes
    - name: Copy config file
      copy:
        src: config
        dest: ~/sunbird-devops/deploy/config
    - name: Install Sunbird Prerequisites
      raw: cd ~/sunbird-devops/deploy && /bin/bash -c ./sunbird_install.sh
